"""Add one to many relationship between posts and users

Revision ID: 25752a46158e
Revises: beb58aaeded8
Create Date: 2022-10-18 23:56:54.864263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25752a46158e'
down_revision = 'beb58aaeded8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_author_fkey', 'post', 'user', ['author'], ['id'])
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
