"""Add post columns

Revision ID: cd61c675ec2e
Revises: 6b8d54a53ef4
Create Date: 2022-10-09 20:31:10.385989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd61c675ec2e'
down_revision = '6b8d54a53ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_filename', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('text', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'])
    op.drop_column('post', 'filename')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('member_since', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('filename', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author')
    op.drop_column('post', 'timestamp')
    op.drop_column('post', 'text')
    op.drop_column('post', 'img_filename')
    # ### end Alembic commands ###
